# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: yarn-rm
  namespace: yarn-cluster
  labels:
    component: yarn-rm
spec:
  ports:
  - port: 8088
    name: web
  - port: 8031
    name: ipc
  - port: 8032
    name: proxy
  # *.yarn-rm.yarn-cluster.svc.cluster.local
  clusterIP: None
  selector:
    component: yarn-rm
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: yarn-rm
spec:
  serviceName: "yarn-rm"
  replicas: 1
  template:
    metadata:
      labels:
        component: yarn-rm
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: yarn-rm
        image: bj-xg-oam-docker-hub-001.tendcloud.com/library/hadoop-2.6.0-cdh5.5.2:v1
        ports:
        - containerPort: 8088
          name: web
        - containerPort: 8031
          name: ipc
        command:
           - "/bin/bash"
           - "/tmp/hadoop-config/bootstrap.sh"
           - "-d"
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1000m"
          limits:
            memory: "10240Mi"
            cpu: "4000m"
        volumeMounts:
          - name: hadoop-config
            mountPath: /tmp/hadoop-config
      volumes:
        - name: hadoop-config
          configMap:
            name: hadoop-config
