# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: zeppelin
  namespace: yarn-cluster
  labels:
    component: zeppelin
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  # *.zeppelin.yarn-cluster.svc.cluster.local
  selector:
    component: zeppelin
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zeppelin
spec:
  serviceName: "zeppelin"
  replicas: 1
  template:
    metadata:
      labels:
        component: zeppelin
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: zeppelin
        image: sz-pg-oam-docker-hub-001.tendcloud.com/library/dylanmei-zeppelin:0.7.0
        ports:
        - containerPort: 8080
          name: web
        env:
        - name: ZEPPELIN_PORT
          value: "8080"
        - name: MASTER
          value: "yarn"
        - name: ZEPPELIN_JAVA_OPTS
          value: >-
            -Dspark.driver.memory=1g
            -Dspark.executor.memory=1g
        - name: SPARK_SUBMIT_OPTIONS
          value: >-
            --deploy-mode client
            --num-executors 2
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1000m"
          limits:
            memory: "4096Mi"
            cpu: "2000m"
        volumeMounts:
          - name: hadoop-config
            mountPath: /usr/hadoop-2.7.2/etc/hadoop
      volumes:
        - name: hadoop-config
          configMap:
            name: hadoop-config
